language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
    - php: 7.4snapshot
    
branches:
  only:
  - /.*/

env:
  - GOOGLE_APPLICATION_CREDENTIALS=~/emptycredentials.json

before_script:
  - composer install
  - pecl install grpc
  - "sudo echo '{\"type\": \"authorized_user\",\"client_id\": \"\",\"client_secret\": \"\",\"refresh_token\": \"\"}' >> $GOOGLE_APPLICATION_CREDENTIALS"

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml
  - vendor/bin/phpcs --standard=phpcs_ruleset.xml -np

after_success:
  - bash <(curl -s https://codecov.io/bash)
